[package]
name = "algorithms-in-rust"
version = "0.1.0"
authors = ["xenowits <kumar.abhishek111b@gmail.com>", "dB2510 <dhruvbodani2510@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
